package com.carFactory.diyCar.mybatis.model;

public class CarModification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR_MODIFICATION.MODIFICATION_ID
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    private Long modificationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR_MODIFICATION.CAR_ID
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    private Long carId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR_MODIFICATION.MODIFICATION_ID
     *
     * @return the value of PUBLIC.CAR_MODIFICATION.MODIFICATION_ID
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    public Long getModificationId() {
        return modificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR_MODIFICATION.MODIFICATION_ID
     *
     * @param modificationId the value for PUBLIC.CAR_MODIFICATION.MODIFICATION_ID
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    public void setModificationId(Long modificationId) {
        this.modificationId = modificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR_MODIFICATION.CAR_ID
     *
     * @return the value of PUBLIC.CAR_MODIFICATION.CAR_ID
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    public Long getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR_MODIFICATION.CAR_ID
     *
     * @param carId the value for PUBLIC.CAR_MODIFICATION.CAR_ID
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    public void setCarId(Long carId) {
        this.carId = carId;
    }
}