package com.carFactory.diyCar.mybatis.model;

public class Modification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODIFICATION.ID
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODIFICATION.NAME
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODIFICATION.TYPE
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODIFICATION.ID
     *
     * @return the value of PUBLIC.MODIFICATION.ID
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODIFICATION.ID
     *
     * @param id the value for PUBLIC.MODIFICATION.ID
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODIFICATION.NAME
     *
     * @return the value of PUBLIC.MODIFICATION.NAME
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODIFICATION.NAME
     *
     * @param name the value for PUBLIC.MODIFICATION.NAME
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODIFICATION.TYPE
     *
     * @return the value of PUBLIC.MODIFICATION.TYPE
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODIFICATION.TYPE
     *
     * @param type the value for PUBLIC.MODIFICATION.TYPE
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    public void setType(String type) {
        this.type = type;
    }
}