package com.carFactory.diyCar.mybatis.model;

public class OriginalMake {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORIGINAL_MAKE.ID
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORIGINAL_MAKE.NAME
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORIGINAL_MAKE.ID
     *
     * @return the value of PUBLIC.ORIGINAL_MAKE.ID
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORIGINAL_MAKE.ID
     *
     * @param id the value for PUBLIC.ORIGINAL_MAKE.ID
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORIGINAL_MAKE.NAME
     *
     * @return the value of PUBLIC.ORIGINAL_MAKE.NAME
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORIGINAL_MAKE.NAME
     *
     * @param name the value for PUBLIC.ORIGINAL_MAKE.NAME
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}