package com.carFactory.diyCar.mybatis.dao;

import com.carFactory.diyCar.mybatis.model.Modification;
import java.util.List;

public interface ModificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODIFICATION
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODIFICATION
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    int insert(Modification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODIFICATION
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    Modification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODIFICATION
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    List<Modification> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODIFICATION
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    int updateByPrimaryKey(Modification record);
}