package com.carFactory.diyCar.mybatis.dao;

import com.carFactory.diyCar.mybatis.model.OriginalMake;
import java.util.List;

public interface OriginalMakeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ORIGINAL_MAKE
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ORIGINAL_MAKE
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    int insert(OriginalMake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ORIGINAL_MAKE
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    OriginalMake selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ORIGINAL_MAKE
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    List<OriginalMake> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ORIGINAL_MAKE
     *
     * @mbg.generated Tue Mar 23 16:57:41 EET 2021
     */
    int updateByPrimaryKey(OriginalMake record);
}